ALTER TABLE users ADD COLUMN email TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN bankroll INTEGER NOT NULL DEFAULT 500;
ALTER TABLE users ADD COLUMN play_seconds INTEGER NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users(email);
